### ISSUE TITLE
Group Settings UI+ Bug

### ISSUE THREAD

**Issue by petersrt** [joehershey/movie-night#33]
Summary: After entering an obscene amount of characters into the fields automatically reverts to whatever was in it before after some time.
Description: It's not clear if this is error catching or just a bug, but I was able to put some crazy maximums in despite 99999999999999 not working. 9,999,999 is probably higher than what is practical for maximums, as for the name being 20+ characters perhaps the user should at least be told what's happening when it doesn't work/reverts
Severity: trivial/enhancement

**Comment by abomberg** [comment]
Fix: gave TextInputs a reasonable max length, user will be prevented from long inputs like this
